# Generated by Django 5.1.4 on 2025-07-26 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrescriptionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(blank=True, max_length=50, verbose_name='Patient Name')),
                ('prescription_date', models.DateField(blank=True, null=True, verbose_name='Prescription Date')),
                ('medications', models.JSONField(default=list, verbose_name='Medications')),
                ('complaints', models.JSONField(default=list, verbose_name='Complaints')),
                ('gender', models.CharField(blank=True, max_length=50, verbose_name='Gender')),
                ('age', models.CharField(blank=True, max_length=50, verbose_name='Age')),
                ('weight', models.CharField(blank=True, max_length=50, verbose_name='Weight')),
                ('bp', models.CharField(blank=True, max_length=50, verbose_name='BP')),
                ('place', models.CharField(blank=True, max_length=50, verbose_name='Place')),
                ('pulse', models.CharField(blank=True, max_length=50, verbose_name='Pulse')),
                ('type', models.CharField(blank=True, max_length=50, verbose_name='Type')),
                ('lab_test', models.JSONField(default=list, verbose_name='Lab Test')),
                ('follow_up_date', models.DateField(blank=True, null=True, verbose_name='Follow up date')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date Updated')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescription_records', to='users.patient', verbose_name='Patient')),
            ],
            options={
                'verbose_name': 'Prescription Record',
                'verbose_name_plural': 'Prescription Record',
                'db_table': 'PrescriptionRecord',
            },
        ),
    ]
