# Generated by Django 5.1.4 on 2025-07-26 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_check_up_charge', models.PositiveIntegerField(default=400)),
                ('follow_up_check_up_charge', models.PositiveIntegerField(default=300)),
                ('one_month_late_check_up_charge', models.PositiveIntegerField(default=400)),
                ('stress_test_charge', models.PositiveIntegerField(default=1900)),
                ('ecg_test_charge', models.PositiveIntegerField(default=1500)),
                ('morning_ect_injection_charge', models.PositiveIntegerField(default=2000)),
                ('injection_in_back_charge', models.PositiveIntegerField(default=600)),
                ('counselling_session_charge', models.PositiveIntegerField(default=1000)),
                ('evening_first_check_up_charge', models.PositiveIntegerField(default=500)),
                ('evening_follow_up_check_up_charge', models.PositiveIntegerField(default=400)),
                ('special_appointment_check_up_charge', models.PositiveIntegerField(default=600)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Clinic Charge',
                'verbose_name_plural': 'Clinic Charges',
                'db_table': 'clinic_charge',
            },
        ),
        migrations.CreateModel(
            name='PatientCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_check_up', models.PositiveIntegerField(default=0)),
                ('follow_up_check_up', models.PositiveIntegerField(default=0)),
                ('one_month_late_check_up', models.PositiveIntegerField(default=0)),
                ('stress_test', models.PositiveIntegerField(default=0)),
                ('ecg_test', models.PositiveIntegerField(default=0)),
                ('morning_ect_injection', models.PositiveIntegerField(default=0)),
                ('injection_in_back', models.PositiveIntegerField(default=0)),
                ('counselling_session', models.PositiveIntegerField(default=0)),
                ('evening_first_check_up', models.PositiveIntegerField(default=0)),
                ('evening_follow_up_check_up', models.PositiveIntegerField(default=0)),
                ('special_appointment_check_up', models.PositiveIntegerField(default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_charge', to='users.patient', verbose_name='Patient')),
            ],
            options={
                'verbose_name': 'Patient Charge',
                'verbose_name_plural': 'Patient Charges',
                'db_table': 'patient_charge',
            },
        ),
    ]
