# Generated by Django 5.1.4 on 2025-07-26 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('image_processing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientcharge',
            name='prescriptionRecord',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_charge', to='image_processing.prescriptionrecord', verbose_name='Prescription Record'),
        ),
    ]
