# Generated by Django 5.1.4 on 2025-07-26 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GenericName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Generic Name')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date Updated')),
            ],
            options={
                'verbose_name': 'Generic Name',
                'verbose_name_plural': 'Generic Name',
                'db_table': 'GenericName',
            },
        ),
        migrations.CreateModel(
            name='MedicineType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Medicine Type Name')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date Updated')),
            ],
            options={
                'verbose_name': 'Medicine Type',
                'verbose_name_plural': 'Medicine Type',
                'db_table': 'MedicineType',
            },
        ),
        migrations.CreateModel(
            name='MedicineData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Medicine Name')),
                ('price', models.CharField(blank=True, max_length=30, null=True, verbose_name='Price')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Quantity')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date Updated')),
                ('generic_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.genericname', verbose_name='Generic Name')),
                ('medicine_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.medicinetype', verbose_name='Medicine Type')),
            ],
            options={
                'verbose_name': 'Medicine Data',
                'verbose_name_plural': 'Medicine Data',
                'db_table': 'MedicineData',
            },
        ),
    ]
